/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScatterTestRouteImport } from './routes/scatter-test'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsThemesRouteImport } from './routes/settings.themes'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsMoonRouteImport } from './routes/settings.moon'
import { Route as SettingsGuidesRouteImport } from './routes/settings.guides'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsBlueprintRouteImport } from './routes/settings.blueprint'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScatterTestRoute = ScatterTestRouteImport.update({
  id: '/scatter-test',
  path: '/scatter-test',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemesRoute = SettingsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMoonRoute = SettingsMoonRouteImport.update({
  id: '/moon',
  path: '/moon',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGuidesRoute = SettingsGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBlueprintRoute = SettingsBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DrawRoute: typeof DrawRoute
  GuidesRoute: typeof GuidesRoute
  JournalRoute: typeof JournalRoute
  ScatterTestRoute: typeof ScatterTestRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scatter-test': {
      id: '/scatter-test'
      path: '/scatter-test'
      fullPath: '/scatter-test'
      preLoaderRoute: typeof ScatterTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/themes': {
      id: '/settings/themes'
      path: '/themes'
      fullPath: '/settings/themes'
      preLoaderRoute: typeof SettingsThemesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/moon': {
      id: '/settings/moon'
      path: '/moon'
      fullPath: '/settings/moon'
      preLoaderRoute: typeof SettingsMoonRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/guides': {
      id: '/settings/guides'
      path: '/guides'
      fullPath: '/settings/guides'
      preLoaderRoute: typeof SettingsGuidesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/blueprint': {
      id: '/settings/blueprint'
      path: '/blueprint'
      fullPath: '/settings/blueprint'
      preLoaderRoute: typeof SettingsBlueprintRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsBlueprintRoute: typeof SettingsBlueprintRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsGuidesRoute: typeof SettingsGuidesRoute
  SettingsMoonRoute: typeof SettingsMoonRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsThemesRoute: typeof SettingsThemesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBlueprintRoute: SettingsBlueprintRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsGuidesRoute: SettingsGuidesRoute,
  SettingsMoonRoute: SettingsMoonRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsThemesRoute: SettingsThemesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DrawRoute: DrawRoute,
  GuidesRoute: GuidesRoute,
  JournalRoute: JournalRoute,
  ScatterTestRoute: ScatterTestRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
