/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScatterTestRouteImport } from './routes/scatter-test'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsPatternIdRouteImport } from './routes/threads.$patternId'
import { Route as StoriesPatternIdRouteImport } from './routes/stories.$patternId'
import { Route as SettingsThemesRouteImport } from './routes/settings.themes'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsMoonRouteImport } from './routes/settings.moon'
import { Route as SettingsGuidesRouteImport } from './routes/settings.guides'
import { Route as SettingsDecksRouteImport } from './routes/settings.decks'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsBlueprintRouteImport } from './routes/settings.blueprint'
import { Route as InsightsYearOfLunationsRouteImport } from './routes/insights.year-of-lunations'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as InsightsRecapLunationStartRouteImport } from './routes/insights.recap.$lunationStart'
import { Route as InsightsCardCardIdRouteImport } from './routes/insights.card.$cardId'
import { Route as HelpCategoryArticleRouteImport } from './routes/help.$category.$article'
import { Route as ApiPublicDetectWeavesRouteImport } from './routes/api/public/detect-weaves'
import { Route as ApiPublicDetectWeavesStatusRouteImport } from './routes/api/public/detect-weaves/status'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScatterTestRoute = ScatterTestRouteImport.update({
  id: '/scatter-test',
  path: '/scatter-test',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsPatternIdRoute = ThreadsPatternIdRouteImport.update({
  id: '/$patternId',
  path: '/$patternId',
  getParentRoute: () => ThreadsRoute,
} as any)
const StoriesPatternIdRoute = StoriesPatternIdRouteImport.update({
  id: '/$patternId',
  path: '/$patternId',
  getParentRoute: () => StoriesRoute,
} as any)
const SettingsThemesRoute = SettingsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMoonRoute = SettingsMoonRouteImport.update({
  id: '/moon',
  path: '/moon',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGuidesRoute = SettingsGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDecksRoute = SettingsDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBlueprintRoute = SettingsBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => SettingsRoute,
} as any)
const InsightsYearOfLunationsRoute = InsightsYearOfLunationsRouteImport.update({
  id: '/year-of-lunations',
  path: '/year-of-lunations',
  getParentRoute: () => InsightsRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const InsightsRecapLunationStartRoute =
  InsightsRecapLunationStartRouteImport.update({
    id: '/recap/$lunationStart',
    path: '/recap/$lunationStart',
    getParentRoute: () => InsightsRoute,
  } as any)
const InsightsCardCardIdRoute = InsightsCardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => InsightsRoute,
} as any)
const HelpCategoryArticleRoute = HelpCategoryArticleRouteImport.update({
  id: '/$category/$article',
  path: '/$category/$article',
  getParentRoute: () => HelpRoute,
} as any)
const ApiPublicDetectWeavesRoute = ApiPublicDetectWeavesRouteImport.update({
  id: '/api/public/detect-weaves',
  path: '/api/public/detect-weaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDetectWeavesStatusRoute =
  ApiPublicDetectWeavesStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiPublicDetectWeavesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/threads': typeof ThreadsRouteWithChildren
  '/admin/usage': typeof AdminUsageRoute
  '/insights/year-of-lunations': typeof InsightsYearOfLunationsRoute
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/decks': typeof SettingsDecksRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/stories/$patternId': typeof StoriesPatternIdRoute
  '/threads/$patternId': typeof ThreadsPatternIdRoute
  '/api/public/detect-weaves': typeof ApiPublicDetectWeavesRouteWithChildren
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/insights/card/$cardId': typeof InsightsCardCardIdRoute
  '/insights/recap/$lunationStart': typeof InsightsRecapLunationStartRoute
  '/api/public/detect-weaves/status': typeof ApiPublicDetectWeavesStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/threads': typeof ThreadsRouteWithChildren
  '/admin/usage': typeof AdminUsageRoute
  '/insights/year-of-lunations': typeof InsightsYearOfLunationsRoute
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/decks': typeof SettingsDecksRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/stories/$patternId': typeof StoriesPatternIdRoute
  '/threads/$patternId': typeof ThreadsPatternIdRoute
  '/api/public/detect-weaves': typeof ApiPublicDetectWeavesRouteWithChildren
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/insights/card/$cardId': typeof InsightsCardCardIdRoute
  '/insights/recap/$lunationStart': typeof InsightsRecapLunationStartRoute
  '/api/public/detect-weaves/status': typeof ApiPublicDetectWeavesStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/draw': typeof DrawRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/journal': typeof JournalRoute
  '/scatter-test': typeof ScatterTestRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/threads': typeof ThreadsRouteWithChildren
  '/admin/usage': typeof AdminUsageRoute
  '/insights/year-of-lunations': typeof InsightsYearOfLunationsRoute
  '/settings/blueprint': typeof SettingsBlueprintRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/decks': typeof SettingsDecksRoute
  '/settings/guides': typeof SettingsGuidesRoute
  '/settings/moon': typeof SettingsMoonRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/stories/$patternId': typeof StoriesPatternIdRoute
  '/threads/$patternId': typeof ThreadsPatternIdRoute
  '/api/public/detect-weaves': typeof ApiPublicDetectWeavesRouteWithChildren
  '/help/$category/$article': typeof HelpCategoryArticleRoute
  '/insights/card/$cardId': typeof InsightsCardCardIdRoute
  '/insights/recap/$lunationStart': typeof InsightsRecapLunationStartRoute
  '/api/public/detect-weaves/status': typeof ApiPublicDetectWeavesStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/help'
    | '/insights'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/stories'
    | '/threads'
    | '/admin/usage'
    | '/insights/year-of-lunations'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/decks'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
    | '/stories/$patternId'
    | '/threads/$patternId'
    | '/api/public/detect-weaves'
    | '/help/$category/$article'
    | '/insights/card/$cardId'
    | '/insights/recap/$lunationStart'
    | '/api/public/detect-weaves/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/help'
    | '/insights'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/stories'
    | '/threads'
    | '/admin/usage'
    | '/insights/year-of-lunations'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/decks'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
    | '/stories/$patternId'
    | '/threads/$patternId'
    | '/api/public/detect-weaves'
    | '/help/$category/$article'
    | '/insights/card/$cardId'
    | '/insights/recap/$lunationStart'
    | '/api/public/detect-weaves/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/draw'
    | '/guides'
    | '/help'
    | '/insights'
    | '/journal'
    | '/scatter-test'
    | '/settings'
    | '/stories'
    | '/threads'
    | '/admin/usage'
    | '/insights/year-of-lunations'
    | '/settings/blueprint'
    | '/settings/data'
    | '/settings/decks'
    | '/settings/guides'
    | '/settings/moon'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/themes'
    | '/stories/$patternId'
    | '/threads/$patternId'
    | '/api/public/detect-weaves'
    | '/help/$category/$article'
    | '/insights/card/$cardId'
    | '/insights/recap/$lunationStart'
    | '/api/public/detect-weaves/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DrawRoute: typeof DrawRoute
  GuidesRoute: typeof GuidesRoute
  HelpRoute: typeof HelpRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  JournalRoute: typeof JournalRoute
  ScatterTestRoute: typeof ScatterTestRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  ThreadsRoute: typeof ThreadsRouteWithChildren
  ApiPublicDetectWeavesRoute: typeof ApiPublicDetectWeavesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scatter-test': {
      id: '/scatter-test'
      path: '/scatter-test'
      fullPath: '/scatter-test'
      preLoaderRoute: typeof ScatterTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$patternId': {
      id: '/threads/$patternId'
      path: '/$patternId'
      fullPath: '/threads/$patternId'
      preLoaderRoute: typeof ThreadsPatternIdRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/stories/$patternId': {
      id: '/stories/$patternId'
      path: '/$patternId'
      fullPath: '/stories/$patternId'
      preLoaderRoute: typeof StoriesPatternIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/settings/themes': {
      id: '/settings/themes'
      path: '/themes'
      fullPath: '/settings/themes'
      preLoaderRoute: typeof SettingsThemesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/moon': {
      id: '/settings/moon'
      path: '/moon'
      fullPath: '/settings/moon'
      preLoaderRoute: typeof SettingsMoonRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/guides': {
      id: '/settings/guides'
      path: '/guides'
      fullPath: '/settings/guides'
      preLoaderRoute: typeof SettingsGuidesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/decks': {
      id: '/settings/decks'
      path: '/decks'
      fullPath: '/settings/decks'
      preLoaderRoute: typeof SettingsDecksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/blueprint': {
      id: '/settings/blueprint'
      path: '/blueprint'
      fullPath: '/settings/blueprint'
      preLoaderRoute: typeof SettingsBlueprintRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/insights/year-of-lunations': {
      id: '/insights/year-of-lunations'
      path: '/year-of-lunations'
      fullPath: '/insights/year-of-lunations'
      preLoaderRoute: typeof InsightsYearOfLunationsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/insights/recap/$lunationStart': {
      id: '/insights/recap/$lunationStart'
      path: '/recap/$lunationStart'
      fullPath: '/insights/recap/$lunationStart'
      preLoaderRoute: typeof InsightsRecapLunationStartRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/card/$cardId': {
      id: '/insights/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/insights/card/$cardId'
      preLoaderRoute: typeof InsightsCardCardIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/help/$category/$article': {
      id: '/help/$category/$article'
      path: '/$category/$article'
      fullPath: '/help/$category/$article'
      preLoaderRoute: typeof HelpCategoryArticleRouteImport
      parentRoute: typeof HelpRoute
    }
    '/api/public/detect-weaves': {
      id: '/api/public/detect-weaves'
      path: '/api/public/detect-weaves'
      fullPath: '/api/public/detect-weaves'
      preLoaderRoute: typeof ApiPublicDetectWeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/detect-weaves/status': {
      id: '/api/public/detect-weaves/status'
      path: '/status'
      fullPath: '/api/public/detect-weaves/status'
      preLoaderRoute: typeof ApiPublicDetectWeavesStatusRouteImport
      parentRoute: typeof ApiPublicDetectWeavesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsageRoute: typeof AdminUsageRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsageRoute: AdminUsageRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HelpRouteChildren {
  HelpCategoryArticleRoute: typeof HelpCategoryArticleRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpCategoryArticleRoute: HelpCategoryArticleRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface InsightsRouteChildren {
  InsightsYearOfLunationsRoute: typeof InsightsYearOfLunationsRoute
  InsightsCardCardIdRoute: typeof InsightsCardCardIdRoute
  InsightsRecapLunationStartRoute: typeof InsightsRecapLunationStartRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsYearOfLunationsRoute: InsightsYearOfLunationsRoute,
  InsightsCardCardIdRoute: InsightsCardCardIdRoute,
  InsightsRecapLunationStartRoute: InsightsRecapLunationStartRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBlueprintRoute: typeof SettingsBlueprintRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDecksRoute: typeof SettingsDecksRoute
  SettingsGuidesRoute: typeof SettingsGuidesRoute
  SettingsMoonRoute: typeof SettingsMoonRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsThemesRoute: typeof SettingsThemesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBlueprintRoute: SettingsBlueprintRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDecksRoute: SettingsDecksRoute,
  SettingsGuidesRoute: SettingsGuidesRoute,
  SettingsMoonRoute: SettingsMoonRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsThemesRoute: SettingsThemesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StoriesRouteChildren {
  StoriesPatternIdRoute: typeof StoriesPatternIdRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesPatternIdRoute: StoriesPatternIdRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface ThreadsRouteChildren {
  ThreadsPatternIdRoute: typeof ThreadsPatternIdRoute
}

const ThreadsRouteChildren: ThreadsRouteChildren = {
  ThreadsPatternIdRoute: ThreadsPatternIdRoute,
}

const ThreadsRouteWithChildren =
  ThreadsRoute._addFileChildren(ThreadsRouteChildren)

interface ApiPublicDetectWeavesRouteChildren {
  ApiPublicDetectWeavesStatusRoute: typeof ApiPublicDetectWeavesStatusRoute
}

const ApiPublicDetectWeavesRouteChildren: ApiPublicDetectWeavesRouteChildren = {
  ApiPublicDetectWeavesStatusRoute: ApiPublicDetectWeavesStatusRoute,
}

const ApiPublicDetectWeavesRouteWithChildren =
  ApiPublicDetectWeavesRoute._addFileChildren(
    ApiPublicDetectWeavesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DrawRoute: DrawRoute,
  GuidesRoute: GuidesRoute,
  HelpRoute: HelpRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  JournalRoute: JournalRoute,
  ScatterTestRoute: ScatterTestRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  ThreadsRoute: ThreadsRouteWithChildren,
  ApiPublicDetectWeavesRoute: ApiPublicDetectWeavesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
